### ISSUE TITLE
What community could do to help?

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/addon-store-submission#4]
I believe making this proposal a reality would be a great milestone for NVDA biggest advantage being native  updates for add-ons, transparent reviews, and hopefully easier additions to the translation system. It is also worth pointing out that at the moment new add-ons are not being added to the translation and in general current reviewers are waiting for NV Access to implement this before submitting new add-ons to the website. It would be great if  you could provide any ETA for this @feerrenrut I understand that it might not be a priority for you therefore I would like to ask what we as a community could do to make this happen in a reasonable time frame - I am thinking rather in a technical terms, as the proposal seems to be discussed enough times and ironing any rough edges might be done  when implementing.

**Comment by feerrenrut** [comment]
Bear in mind that this proposal is concerning itself with acceptance of new add-on releases into a data store as opposed to the translation process, which we will look at separately. For translations we'll look at how we can update the NVDA translation process first, keeping in mind that this should also be adaptable to add-ons.

In terms of this proposal, the biggest unknown at the moment is how we go from an add-on commit that has been reviewed to producing an installable URL for the add-on. It would be ideal if this process ensured that the addon URL was built from the commit. It should just be a matter of zipping up the repo itself. Extra dll's that the addon needs could be pulled with submodules or built with a github actions. This may mean that some authors will have to restructure their repositories somewhat, exploring the implications of this would be good.

We may decide to skip that whole step initially, but knowing what is possible will be helpful when we get to it.

**Comment by lukaszgo1** [comment]
Could you say anything about the ETA - I understand that it might be hard to say anything  concrete but even knowing if we are talking about a month or a year might help. Regarding creating archives my first thought would be to require add-on authors to provide appveyor file which builds their add-on - simple zipping is a step backwards it eliminates all advantages of add-on template.

**Comment by feerrenrut** [comment]
I can't give a proper ETA at this stage, but I expect within 6 months. 

> simple zipping is a step backwards it eliminates all advantages of add-on template.

Can you expand on this for me? I'm not entirely sure I understand what would be eliminated?

**Comment by lukaszgo1** [comment]
For most add-ons the documentation and translations of both manifest and user interface messages are not stored in the compiled version in the repo but are being created as part of scons just before add-on files are being archived in the .nvda-addon file. I can also imagine that for some add-ons sconscript is used to include additional files - the only examples which  comes  to  mint ATM is NVDA Remote (executable required to handle url's is being build when scons executes), but there are probably more add-ons doing it i.e. when additional Python packages not included in NVDA are required.

**Comment by nvdaes** [comment]
About the subject of this issue, related to community help, I would like to aknowledge the work made by @mhameed (with some collaboration from me), which may be helpful. In particular, using GitHub Actions to perform tasks like:

* Ensure that an add-on repo is using the latest version of the addonTemplate. Otherwise, a comment is sent by GitHub Actions to the corresponding PR.
* Check if py files contains BOM character, which may cause problems with gettext.
* Create releases and build/upload binaries when pushing tags (we can create prereleases for instance when tag ends with -dev).
* Lint markdown files (maybe useful for readability, at least for readme.md in English.
* Use flake8 to lint Python files.
See workflows at
<https://github.com/nvdaaddons/l10ntest>

**Comment by nvdaes** [comment]
Replying to @lukaszgo1  
> I can also imagine that for some add-ons sconscript is used to include additional files 

Now I'm thinking that some kind of form (likely with an issue template) could be used to include dependencies required by add-ons. If we use GitHub Actions, a workflow could be included to download or install specific dependencies. I haven't used scons scripts for this, so I am not sure, but workflows are single yaml files and maybe easy to manage.
From a possible dependencies.yaml file, we can invoque:
run: |
  curl ... <someUrl>
pip install <somePackage>
  scons

**Comment by feerrenrut** [comment]
While I still think it would be ideal to be able to verify that an add-on download is the same as the code that was reviewed we may initially skip this requirement, since it would be new anyway. Instead, a download URL can be used. A secure hash in the metadata for that add-on release will ensure that the URL still points to the files initially reviewed. 

> While I still believe that simply zipping content of the commit is not a way to go - translation and documentation would not be build that way

If we tried to pursue the requirement (being able to prove the addon package is built unmodified from a commit) there are a variety of ways to solve this problem. Add-ons could have a 'release-ready' branch that gets a commit from a github action for every commit to master. This action would collect documentation and translations, and merge them with master in an appropriate way to create a "just zip me" add-on package content.

**Comment by lukaszgo1** [comment]
This is not really actionable - closing
